### ISSUE TITLE
lotusphp集成进项目后异常问题

### ISSUE THREAD

**Issue by lyongde** [qinjx/lotusphp#22]
你好，使用支付宝面对面支付包(PHP版)：https://t.alipayobjects.com/L1/92/1088/1436969897296.zip?spm=0.0.0.0.uj5ax1&file=1436969897296.zip，require_once f2fpay/F2fpay.php文件后，出现以下异常：

1、C方法和系统内部C方法冲突；

2、require_once f2fpay/F2fpay.php文件后，Fatal error异常：
<br />
<b>Fatal error</b>: Uncaught exception 'Shopnc\Exception' with message 'Class Error: cannot autoload class: LtObjectUtil' in /data/wwwroot/mobile/api/payment/alipay_saoma/lotusphp_runtime/Lotus.php:123
Stack trace:
#0 [internal function]: Shopnc\Core::autoload('LtObjectUtil')
#1 /data/wwwroot/mobile/api/payment/alipay_saoma/lotusphp_runtime/Lotus.php(123): spl_autoload_call('LtObjectUtil')
#2 /data/wwwroot/mobile/api/payment/alipay_saoma/lotusphp_runtime/Lotus.php(84): Lotus-&gt;prepareConfig()
#3 /data/wwwroot/mobile/api/payment/alipay_saoma/AopSdk.php(43): Lotus-&gt;init()
#4 /data/wwwroot/mobile/api/payment/alipay_saoma/f2fpay/F2fpay.php(2): require_once('/data/wwwroot/v...')
#5 /data/wwwroot/mobile/api/payment/alipay_saoma/alipay_saoma.php(13): require_once('/data/wwwroot/v...')
#6 /data/wwwroot/mobile/control/member_payment.php(200): alipay_saoma-&gt;get_payurl(Array)
#7 /data/wwwroot/mobile/control/member_payment.php(73): in <b>/data/wwwroot/mobile/api/payment/alipay_saoma/lotusphp_runtime/Lotus.php</b> on line <b>123</b><br />

**Comment by iuyes** [comment]
可以修改Lotusphp的内置C方法，改名即可
